inherit: true

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
