language: php

matrix:
  include:
    - php: 7.4
      env:
        - SS_ENVIRONMENT_TYPE=dev
        - SS_DATABASE_CLASS=SQLite3Database
        - SS_DATABASE_NAME=xxx
        - SS_DATABASE_USERNAME=xxx
        - SS_DATABASE_PASSWORD=xxx
        - SS_DEFAULT_ADMIN_USERNAME=admin
        - SS_DEFAULT_ADMIN_PASSWORD=admin
        - RECIPE_VERSION=4.10.x-dev
    - php: 8.0
      env:
        - SS_ENVIRONMENT_TYPE=dev
        - SS_DATABASE_CLASS=SQLite3Database
        - SS_DATABASE_NAME=xxx
        - SS_DATABASE_USERNAME=xxx
        - SS_DATABASE_PASSWORD=xxx
        - SS_DEFAULT_ADMIN_USERNAME=admin
        - SS_DEFAULT_ADMIN_PASSWORD=admin
        - RECIPE_VERSION=4.10.x-dev

before_script:
  - composer validate
  - composer require --no-update silverstripe/framework:"$RECIPE_VERSION"
  - composer install --no-interaction --verbose --profile

script: composer validate
